### ISSUE TITLE
TODOs (or a very loose roadmap)

### ISSUE THREAD

**Issue by that-hatter** [that-hatter/scrapi-searcher#4]
## Enhancements
- [x] add level/rank/scale/attribute icons as custom emotes
- [x] add card artwork thumbnail embeds
  - [x] default pics from the edopro pics server
  - [ ] hq pics
- [x] support card searches using passcodes starting with `c`
- [x] automatically fetch missing konami ID and add it to [the json file](https://github.com/that-hatter/scrapi-searcher/blob/master/data/konamiIds.json).
- [ ] improve `,stage` command
  - [ ] allow creating cdb without a greenlight issue, by adding card names and passwords manually
  - [ ] support rush cards
  - [ ] support tokens by parsing them from the card descriptions
  - [ ] fetch the artworks (and generate proxies?)
- [ ] make certain buttons and menus expire after some time
- [ ] preview function type and table type signatures
- [ ] support filters in search queries
- [x] make bot friendlier to self-hosting
  - [x] allow disabling features for non-Ignis staff hosters
  - [x] load app emojis on startup instead of hardcoding them
  - [x] pass repos as env variables instead of having them in the source code
- [ ] slash commands?

## New Commands
- [x] `,status`/`,version` - Check the bot's version as well as the current version of its loaded data (yard, babel, etc.)
- [x] `,ydke`/`,deck` - Previews a decklist from a ydk file or a ydke string.
- [ ] `,newbanlist` - Creates a banlist from a ydk file or ydke string. Optionally, it can accept a "base" banlist and creates a new one by applying the new changes to that base banlist.
- [ ] 🛡️ `,newarchetype` - Adds a new archetype to all the relevant repos (CardScripts, DeltaPuppetOfStrings, scrapiyard, Datacorn?).
- [ ] `,yugi`/`,pedia` - Search yugipedia.
- [ ] `,apisearch` - Search api documentation by summaries and descriptions rather than name.
